"""allow pending documents without storage key

Revision ID: 39da3f9f768c
Revises: 0337d7d7ae54
Create Date: 2026-10-04 22:02:27.366936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39da3f9f768c'
down_revision: Union[str, Sequence[str], None] = '0337d7d7ae54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 's3_key',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 's3_key',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)
    # ### end Alembic commands ###
